import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function isWordNotAllowed(word: string) {
  return (
    service_words.includes(word.trim().toLowerCase()) ||
    service_words.includes(word.trim().toUpperCase())
  )
}

export const service_words = [
  "admin",
  "user",
  "add",
  "edit",
  "delete",
  "create",
  "update",
  "remove",
  "manage",
  "settings",
  "dashboard",
  "profile",
  "login",
  "logout",
  "register",
  "password",
  "email",
  "api",
  "public",
  "private",
  "authorize",
  "authenticate",
  "permission",
  "role",
  "system",
  "report",
  "analytics",
  "debug",
  "maintenance",
  "backup",
  "restore",
  "log",
  "audit",
  "error",
  "notification",
  "message",
  "support",
  "feedback",
  "terms",
  "policy",
  "documentation",
  "faq",
  "help",
  "about",
  "contact",
  "home",
  "search",
  "result",
  "page",
  "news",
  "blog",
  "article",
  "tutorial",
  "demo",
  "download",
  "upload",
  "image",
  "video",
  "audio",
  "file",
  "document",
  "product",
  "service",
  "pricing",
  "subscribe",
  "unsubscribe",
  "checkout",
  "payment",
  "order",
  "cart",
  "wishlist",
  "shipping",
  "return",
  "refund",
  "confirm",
  "complete",
  "success",
  "error",
  "notification",
  "message",
  "warning",
  "info",
  "alert",
  "confirm",
  "prompt",
]
